import React from 'react';
import Footer from './footer'
import Header from './header'
import './styles.css'
const Terms = () =>{
  return (
    <div className='main'>
      <h1 style={{ color: 'black' }}>Terms & Condition</h1><br /><br />
      <p>Applicable To All Users</p>
<p>Acceptance of Terms</p>
<p>By using the Centre for Traditional Education website and website management system you, (hereinafter referred to as the “User” or “Users”) agree to all terms, conditions, and notices contained or referenced in these Terms of Use (“Terms”).</p>
<p>These Terms apply to your use of Centre for Traditional Education and all materials, information, software, content, products, and services that are owned or endorsed by Centre for Traditional Education, a brand of Tamaltree Enterprises Pvt Ltd, as well as any content, owned or licensed by a 3rd party content provider that is included in, or available through Centre for Traditional Education with that 3rd party’s permission.</p>
<p>If the User is a minor, he or she shall be the responsibility of his or her parent/guardian, who shall ensure that the User adheres to the Terms. Any 3rd Party Content uploaded or otherwise made available by a 3rd Party is and remains the sole property of the 3rd Party or the 3rd Party licensors. By uploading or otherwise making available any 3rd Party Content, you automatically grant and/or warrant that the owner has granted Centre for Traditional Education the perpetual royalty-free, non-exclusive right and license to use, reproduce, publish, distribute, display, and transmit the 3rd Party Content through the channel into which you have uploaded or authorized Centre for Traditional Education to upload the 3rd Party Content. You also permit any User of Centre for Traditional Education with access to that channel, subject to your restrictions, to access, view, store, and reproduce the 3rd Party Content to the same extent permitted herein. To the extent provided for in the specific terms of the governing agreement between Centre for Traditional Education and 3rd Party, 3rd Party Content may be removed, obscured, altered, or modified by the 3rd Party, subject to the terms and conditions set forth herein with respect to the use of Centre for Traditional Education.</p>
<p>Centre for Traditional Education reserves the right to change these Terms at any time, effective upon posting the updated Terms on the Centre for Traditional Education website. The most current version is always available by clicking on the Terms of Use link located at the bottom of the Centre for Traditional Education website.</p>
<p>Centre for Traditional Education is to be used for the purpose of accessing the online education program licensed by or for the benefit of the User(s). Centre for Traditional Education grants the User the non-exclusive, non-transferable, limited license to access, visit, use, view, and print the Content, solely for the User’s own personal non-commercial use in connection with such education program, provided the User keeps intact all copyright and other proprietary notices. Use of the Content or materials for any purpose not expressly permitted in these Terms is prohibited.</p>
<p>Users may not (1) remove, obscure, or alter the Content in any way except as agreed to in writing by the Centre for Traditional Education, (2) use Centre for Traditional Education in any manner that could damage, disable, overburden, or impair any Centre for Traditional Education website or the network(s), 3) gain or attempt to gain unauthorized access to any accounts, computer systems, or networks connected to any Centre for Traditional Education website or systems through hacking, password mining, or any other means, or 4) obtain or attempt to obtain any materials or information through any means not intentionally made available through Centre for Traditional Education.</p>
<p>Any use of the Centre for Traditional Education for the following purposes is strictly prohibited. By using the Centre for Traditional Education website/ e-session program you agree that you will NOT</p>
<p>    Send, receive, or display pornographic, obscene, sexually explicit material, or any material harmful to minors<br />
    impersonate any person or entity (through the use of their password or other means), including any employee or representative of the Centre for Traditional Education.<br />
    Copy or distribute content included in Centre for Traditional Education (including postings on the Updates, WebMail messages, or curriculum materials, including answer keys) without the owner’s permission<br />
    solicit or collect information about the Users or members of this site, especially for the purpose of transmitting, or facilitating transmission of, unsolicited or bulk electronic email or communications<br />
    use the school-provided communication services in connection with surveys, contests, pyramid schemes, chain letters junk e-mail, spamming, or any duplicative or unsolicited messages (commercial or otherwise)<br />
    upload files that contain viruses, Trojan horses, worms, time bombs, cancel bots, corrupted files, or any other similar software or programs that may damage the operation of another’s computer or property<br />
    solicit or collect personal information (including name, address, and phone number) from anyone under eighteen (18) years of age without verified parental consent<br />
    display threatening or offensive material, including using swear words, offensive, vulgar, or obscene language<br />
    display racist, prejudiced, or discriminatory messages or pictures<br />
    violate any state or local law<br />
    reveal another User’s or a minor’s personal address, phone number, or similar information to others without their consent or verified parental consent<br />
    violate any copyright, trademark, patent, trade secret, or other intellectual property laws or otherwise use the intellectual property of another individual or entity without the owner’s permission—this includes providing links to and including other copyrighted or trademarked material from third parties in Centre for Traditional Education.<br />
    trespass in another’s folders, work, or files<br />
    promote commercial activities except as agreed to in writing by the office of Centre for Traditional Education, a brand of Tamaltree Enterprises Pvt Ltd.<br />
    advertise products or services or engage in political lobbying<br />
    defame, harass, insult, abuse, stalk, threaten, attack, or otherwise violate the legal rights (such as privacy and publicity) of another person or interfere with another person’s work, including, but not limited to, sending unwanted WebMail messages or e-mail Each User will have a user name and password (the “Log-in Information”) for the purpose of accessing Centre for Traditional Education and the Content. Users must keep all Log-in Information strictly confidential, and all Log-in Information may be used only by the assigned User. Users are responsible for maintaining the security and confidentiality of all Log-in Information and for preventing access to Centre for Traditional Education and/or the Content by unauthorized persons using a User’s Log-in Information. Users are responsible for any and all activities that occur under their account. Users must notify the Centre for Traditional Education immediately of any unauthorized use of their account or any other breach of security. Notwithstanding the foregoing, certain employees of the Centre for Traditional Education will be permitted to “log in as” someone other than themselves, after receiving the approval of their supervisor and undergoing specific training</p>
<p>Proprietary Rights</p>
<p>The User acknowledges and agrees that certain of the information available in Centre for Traditional Education is protected by various copyrights, trademarks, service marks, patents, trade secrets, or other intellectual property rights and laws and may only be used as permitted by law and with the permission of the owner. Except as expressly Centre for Traditional Education authorized by Centre for Traditional Education, Users may not sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit, or create derivative works from or otherwise exploit the Content or features in CENTRE FOR TRADITIONAL EDUCATION in any form or medium.</p>
<p>Users are fully responsible for their own use and for ensuring such use does not infringe on the rights of the Centre for Traditional Education or third parties. In addition to potential legal action, any unauthorized use including copying or reposting of CENTRE FOR TRADITIONAL EDUCATION or third-party intellectual property may result in one or more of the following: termination of access to Centre for Traditional Education, school-based disciplinary action, and/or removal from the school, course offering or program of study.</p>
<p>Copyright Infringement</p>
<p>Content is owned or controlled by the Centre for Traditional Education or the third party credited as the provider of the Content, and its contents may not be copied, reproduced, distributed, or modified in any way without the express written consent of the Centre for Traditional Education. If you have any copyright concerns about any materials posted on the Centre for Traditional Education by others, please let us know. We comply with the provisions of the Copyright Act applicable to Internet service providers.</p>
<p>Links</p>
<p>Centre for Traditional Education may contain links to other websites or other resources that are provided for the User’s convenience. Unless otherwise noted, these linked sites are not under the control of the Centre for Traditional Education and the Centre for Traditional Education is not responsible for the content available on third-party-linked sites. Centre for Traditional Education makes no representations, warranties, or other commitments whatsoever about any third-party websites or third-party resources that may be referenced, accessible from, or linked to the Centre for Traditional Education. A link to a website does not mean that the Centre for Traditional Education endorses the content, the website owner, or the use of such a website. In addition, the Centre for Traditional Education is not a party to or responsible for any transactions the User may enter into with third parties, even if the User learns of such parties (or uses a link to such parties) from the Centre for Traditional Education. Accordingly, the User acknowledges and agrees that Centre for Traditional Education is not responsible for the availability of such external websites or resources, except where specifically contracted for, and is not responsible or liable for any content, services, products, or other materials on or available from those websites or resources.</p>
<p>Privacy</p>
<p>You agree that your use of the Centre for Traditional Education is also subject to the Privacy Policy, which is part of these Terms.</p>
<p>Mobile Terms &#038; Conditions</p>
<p>By opting in to receive text message alerts from the Centre for Traditional Education, you consent to receive important information regarding your student’s enrollment via text or SMS messages at the mobile phone number you provided. Such calls or texts may be placed using automatic dialing equipment. Message and data rates may apply.</p>
<p>Disclaimer of Warranty</p>
<p>USE OF THE CENTRE FOR TRADITIONAL EDUCATION OR ANY COMMUNICATION SERVICE IS AT THE USER’S SOLE RISK. ALL MATERIALS, INFORMATION, PRODUCTS, SOFTWARE, PROGRAMS, AND SERVICES ARE PROVIDED “AS IS,” WITH NO WARRANTIES OR GUARANTEES WHATSOEVER. CENTRE FOR TRADITIONAL EDUCATION EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT PERMITTED BY LAW ALL EXPRESS, IMPLIED, STATUTORY, AND OTHER WARRANTIES, GUARANTEES, OR REPRESENTATIONS, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY AND INTELLECTUAL PROPERTY RIGHTS. WITHOUT LIMITATION, THE CENTRE FOR TRADITIONAL EDUCATION MAKES NO WARRANTIES OR GUARANTEES THAT THE CENTRE FOR TRADITIONAL EDUCATION WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE. THE USER UNDERSTANDS AND AGREES THAT IF THE USER DOWNLOADS OR OTHERWISE OBTAINS MATERIALS, INFORMATION, PRODUCTS, SOFTWARE, PROGRAMS, OR SERVICES, THE USER DOES SO AT THE USER’S OWN DISCRETION AND RISK AND THAT USER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGES THAT MAY RESULT, INCLUDING LOSS OF DATA OR DAMAGE TO THE USER’S COMPUTER SYSTEM. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO THE USER.</p>
<p>Limitation &#038; Liability</p>
<p>UNDER NO CIRCUMSTANCES WILL THE CENTRE FOR TRADITIONAL EDUCATION, A UNIT OF TAMALTREE ENTERPRISES PVT LTD, BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF OR INABILITY TO USE CENTRE FOR TRADITIONAL EDUCATION OR ANY COMMUNICATION SERVICE.</p>
<p>Release</p>
<p>THE USER HEREBY RELEASES AND FOREVER DISCHARGES CENTRE FOR TRADITIONAL EDUCATION, ITS AFFILIATES, EMPLOYEES, CONTRACTORS, OFFICERS AND DIRECTORS, AGENTS, SUCCESSORS, AND ASSIGNS (“RELEASED PARTIES”), FROM ALL ACTIONS, CAUSES OF ACTION, INJURIES, CLAIMS, DAMAGES, COSTS, OR EXPENSES OF ANY KIND GROWING OUT OF OR RELATED TO THE USER OR USER’S MINOR CHILD(REN)’S USE OF CENTRE FOR TRADITIONAL EDUCATION OR ANY COMMUNICATION SERVICE. THE USER UNDERSTANDS THAT THIS IS A FULL AND COMPLETE RELEASE TO THE MAXIMUM EXTENT ALLOWED BY LAW OF ALL CLAIMS AND DAMAGES TO WHICH YOU OR YOUR MINOR CHILD(REN) MAY HAVE AS A RESULT OF HIS OR HER USE OF A CENTRE FOR TRADITIONAL EDUCATION REGARDLESS OF THE SPECIFIC CAUSE THEREOF.</p>
<p>Termination of use</p>
<p>If the User violates these Terms, the User may be barred from future use of CENTRE FOR TRADITIONAL EDUCATION and/or subject to legal action. Cause for such suspension, termination and/or deletion shall include, but not be limited to,</p>
<p>    breaches or violations of the Terms, or of other incorporated agreements or guidelines,<br />
    requests by law enforcement or other government agencies,<br />
    a request by you (self-initiated account deletions),<br />
    discontinuance or material modification of CENTRE FOR TRADITIONAL EDUCATION (or any part thereof),<br />
    unexpected technical or security issues or problems,<br />
    extended periods of inactivity, and/or<br />
    engagement by you in fraudulent or illegal activities. Termination of your account may include (x) removal of access to all offerings within CENTRE FOR TRADITIONAL EDUCATION, (y) deletion of your password and all related information, files and content associated with or inside your account (or any part thereof), and (z) barring of further use of CENTRE FOR TRADITIONAL EDUCATION.</p>


    </div>
  );
}

export default Terms;
